### ISSUE TITLE
UI is not showing properly

### ISSUE THREAD

**Issue by AyshaLyre** [adrian-miasik/unity-pomodoro#104]
## Description
I don't exactly know what the bug is since I only downloaded it from the Play Store then came across this issue with the UI.

## Reproduction Steps
1. Open the app
2. Then the issue shows

## Impacted Version(s)
- Version: 2.4.1

## Impacted Platform(s)
- Android

![325345147_2293176434177747_1481052129488721204_n](https://user-images.githubusercontent.com/124494888/216814529-74980675-6101-4ca5-b20f-bef994297cde.jpg)

**Comment by adrian-miasik** [comment]
Hey there @AyshaLyre,

I got your email as well. I'll reply to it soon!

But yes, this seems to be an issue with Unity's cloud builder and it is something I am aware of.
Thank you for creating a proper ticket for it. I'll get on fixing this right away.

However, if you're looking for a working build **right now** then I suggest you use the previous Android build version v2.0.0. You can find the Android build in the releases tab or download it here: https://github.com/adrian-miasik/unity-pomodoro/releases/download/v2.2.0/unity-pomodoro-2.2.0-android.apk

Android v2.2.0 seems to be working on my end with no visual artifacts, 
but if you run into any issues, please don't hesitate to let me know.

But yeah, I'll compile a proper 2.4.1 Android build right away and will report back when its uploaded.

Thanks again for reporting this. :)

**Comment by adrian-miasik** [comment]
Hmm, actually scratch that. Just tried Android v2.2.0, also running into the same issue.

Bear with me. I'm on it.

**Comment by adrian-miasik** [comment]
Quick update.

I've uploaded a proper working Android build on the v2.4.1 releases page. You can download it here:
https://github.com/adrian-miasik/unity-pomodoro/releases/download/v2.4.1/unity-pomodoro-2.4.1-android.apk

If you run into an "App not installed" error on Android, let me know.

Working on getting the build up on the Google Play Store, will report back when that is live.

**Comment by adrian-miasik** [comment]
I've lost the upload keystore file which is necessary for signing Android builds and uploading to the Google Play Store. My Unity cloud build configuration is still valid and capable of signing a release build with it's cached keystore file and credentials...but it seems that Unity cloud builds causes these visual artifacts which is unfortunate/a no-go.

I can build an Android version just fine locally, and it solves the visual issue...but I'm unable to sign the build for release locally. So it looks like I won't be able to provide/update the Google Play Store build just yet. The build in my previous comment should work though.

I've contacted Google Play Support on the matter and will be working through it, but it seems like this will take a couple days at the very least.

Lesson learned: Back-up keystore files (Not just the credentials).

Will report back with any updates.

**Comment by AyshaLyre** [comment]
Hey sorry for replying late! I already tried the apk file you gave me and it's working great on my device. I guess the issue only shows on the build on the Play Store. I appreciate your effort in fixing this. Thanks a lot!!

**Comment by adrian-miasik** [comment]
Awesome, that's great news! 👍

Yeah the build on the Google Play Store still needs replacing.
Timelines looking like it'll be solved on this upcoming weekend. (So the 10th or 11th)
I'll keep this issue open until it's solved there too.

But glad to hear the app works on your device now.
Let me know if you have any thoughts or things you'd like to see in the app as well. 
Always open to feedback.

**Comment by AyshaLyre** [comment]
Yes thanks for that! Will patiently wait for the update when it's done ;))

**Comment by adrian-miasik** [comment]
Good news!

I've managed to upload the fixed build onto the Google Play Store.
Rollout has already started and is now shipping out to users.

While the UI is showing properly for the most part, the credits bubble still has a visual bug/artifact.
There's a two circle cutout on the credits bubble, but it shouldn't affect the functionality of the app.

I'll look into that at a later date, but I'm marking this issue as fixed.
Thanks again for the bug report!
