### ISSUE TITLE
FPS unlimited when program is in the background

### ISSUE THREAD

**Issue by damonsmithies** [adrian-miasik/unity-pomodoro#96]
I can see that the program is limited to 240fps when in the foreground, however, when in the background, this currently runs uncapped at 1900FPS.

99% of the time, the application is in the background.

Cheers

**Comment by adrian-miasik** [comment]
Heya there @damonsmithies,

I'll take on this ticket. Can you please confirm what version you are on?

IIRC the framerate should be set to 0 or 1 FPS when the application is not in focus. 
And when the application is in focus, it should set to your monitors refresh rate which seems to be working fine.

I'll see if it's happening on my end on the latest version. I suspect the target framerate of 0 means it's still uncapped...

**Comment by adrian-miasik** [comment]
Can confirm, issue persists in v2.4.0. Will be opening a PR addressing this shortly.

**Comment by damonsmithies** [comment]
Hey sorry for not getting back earlier:

Build ID: 10179694 on Steam!

**Comment by adrian-miasik** [comment]
No worries! I've managed to pin point the bug. Thanks for bringing this to my attention.

**Comment by adrian-miasik** [comment]
PR is up and ready. I'll be adding it to the next hotfix/release. I'll probably get another version out in a weeks time. Thanks again.

**Comment by damonsmithies** [comment]
Hey no problem thanks for resolving.

**Comment by adrian-miasik** [comment]
Latest release (v2.4.1) is out with the appropriate fix:
https://github.com/adrian-miasik/unity-pomodoro/releases/tag/v2.4.1

Marking issue as complete, if it continues to appear in the latest version. Please re-open this ticket.
